### ISSUE TITLE
Tracks table mismatch between specification and implementation

### ISSUE THREAD

**Issue by gsergeant** [CellMigStandOrg/Tracks#15]
When reviewing the [specification here](https://github.com/CellMigStandOrg/Tracks/blob/master/v0.1/index.md), more specifically the Splitting example:

![Split](https://github.com/CellMigStandOrg/Tracks/raw/master/v0.1/images/Split.png)

 The `tracks table` looks like this:

|  Track_ID  |  Link_ID  |
|-------|-------|
| 1 | 1 |
| 1 | 2 |
| 2 | 2 |
| 3 | 1 |

However, this is inconsistent with how we have currently decided to handle tracks and links. 
A tracks table is not a `MUST` requirement, so it is currently not created in any of [these examples](https://github.com/CellMigStandOrg/cell_track_dpkg/tree/spec_0.1/examples). 

Correct me if I'm wrong, but I believe the way we were planning to encode tracks is to have links belong to one, and only one track (no duplication of links in the table). This would mean that a `track` then encompasses all of the `links` that connect an `object` over (one/several) `events`.

The above table would then look like:

|  Track_ID  |  Link_ID  |
|-------|-------|
| 1 | 1 |
| 1 | 2 |

Does this make sense, also having any subsequent track analysis in mind?

**Comment by pcmasuzzo** [comment]
Thanks for this @gsergeant .

There is indeed a divergence between [spec0.1](https://github.com/CellMigStandOrg/Tracks) and [library implementing spec0.1](https://github.com/CellMigStandOrg/cell_track_dpkg/tree/spec_0.1).

One could argue this is an issue in the library, and not in the spec.
However, I believe we want to go for the strategy the library is currently implementing, as @gsergeant suggested: 
`1:n` relationship from `tracks` to `links` (and _**not**_ `n:n`).

If we all agree on this, the spec can be easily fixed.
Thoughts?

**Comment by simleo** [comment]
I also agree. The tracks table should be the latter (one track). The former looks very confusing to me.

**Comment by sbesson** [comment]
The proposal above makes sense to me especially as the tracks are implicit as per the specification.

Had a call with @pcmasuzzo earlier today regarding milestones/timelines, I would propose to:
- freeze the 0.1 specification as of the current `master` branch, tag it and create a GitHub release (probably also create a Zenodo URL as in MIACME)
- create a 0.2 milestone where this issues could be assigned and resolved. The biggest todo for the 0.2 milstone would be to migrate the specification of the tabular data package-based file format implementing the Tracks specification into this repository and address issues such as https://github.com/CellMigStandOrg/cell_track_dpkg/issues/8 for this milestone. The https://github.com/CellMigStandOrg/cell_track_dpkg/ repository would mostly hosting the implementation/translational library for this file format. Any thought/veto/alternative solution?

**Comment by simleo** [comment]
If the current example track tables are inconsistent with the spec, it might be better to fix them before tagging.

**Comment by pcmasuzzo** [comment]
Thanks @sbesson. I agree with the strategy you delineate. 
I also understand @simleo point of view, though. We might want to fix the discrepancy between the Python library and the spec 0.1 before freezing and tagging (namely, tracks examples are encoded differently in the two, even if tracks are implicit, of course).

Therefore, I suggest we do the following:
- fix `tracks tables` in here with a PR (I can do this, if okay)
- freeze, tag and release 0.1
- start working on 0.2 with the timeline/issues above.

What do you say?

**Comment by sbesson** [comment]
If the fix is straightforward, :+1: for addressing it and tagging immediately.

**Comment by sbesson** [comment]
Closing as per #17
