### ISSUE TITLE
Closing gaps by associating segments into a single track is ambiguous

### ISSUE THREAD

**Issue by mkitti** [CellMigStandOrg/Tracks#6]
In the gap closing example, segment 1 links object 1 in frame 1 to object 2 in frame 2, and segment 2 links object 3 in frame 4 to object 4 in frame 5. The implication for gap closing in this example is to associate object 2 in frame 2 with object 3 in frame 4.  The proposed way to do this is to assign segments 1 and 2 to the same track. 

This seems inconsistent with the track grouping in the split and merge examples where the connectivity is explicit. The problem particularly arises when a single track experiences a combination of either of a split or merge and a gap closing event.

For example, in the split event example, imagine if the detection algorithm failed to identify object 3 in frame 3. However, we still want to link object 2 in frame 2 with object 5 in frame 4.

#### A split event with gap closing
A split event with gap closing looks like this:

![Split](images/Split.png){:class="img-responsive"}

The **objects table** in this case is:

Object_ID  |  Frame  |  X |  Y
-----------|---------|----|-----
1          |    1    |    |  
2          |    2    |    |  
4          |    3    |    |
5          |    4    |    |
6          |    4    |    |
7          |    5    |    |
8          |    5    |    |

The **segments table** is:

Segment_ID |  Object_ID
-----------|------------
 1         |    1
 1         |    2
 3         |    5
 3         |    7
 2         |    2
 2         |    4
 2         |    6
 2         |    8

The corresponding **tracks table** is:

 Track_ID |  Segment_ID
 ---------|------------
  1       |    1
  1       |    2
  1       |    3
  2       |    2
  3       |    1

By merely assigning segments 1, 2, and 3 to track 1, is it clear that the gap to be closed is between object 2 and object 5?

I propose requiring that this be explicit via one of three modifications to the segments table, which all could be valid. In each case, linking between segments is explicit due to overlap of object references or continuation of the segment which is by definition linear though not necessarily continuous.

A. The **segments table** is:

Segment_ID |  Object_ID
-----------|------------
 1         |    1
 1         |    2
 1         |    5
 3         |    5
 3         |    7
 2         |    2
 2         |    4
 2         |    6
 2         |    8

B. The **segments table** is:

Segment_ID |  Object_ID
-----------|------------
 1         |    1
 1         |    2
 3         |    2
 3         |    5
 3         |    7
 2         |    2
 2         |    4
 2         |    6
 2         |    8

C. The **segments table** is:

Segment_ID |  Object_ID
-----------|------------
 1         |    1
 1         |    2
 1         |    5
 1         |    7
 2         |    2
 2         |    4
 2         |    6
 2         |    8

### Isolated Gap-closing

Thus for the isolated gap-closing example, the segments table should be modified in one of three ways:

A. The **segments table** is:

Segment_ID |  Object_ID
-----------|------------
 1         |    1
 1         |    2
 1         |    3
 2         |    3
 2         |    4

B. The **segments table** is:

Segment_ID |  Object_ID
-----------|------------
 1         |    1
 1         |    2
 2         |    2
 2         |    3
 2         |    4

C. The **segments table** is:

Segment_ID |  Object_ID
-----------|------------
 1         |    1
 1         |    2
 1         |    3
 1         |    4

### Meaning of Tracks

What then does it mean when segments belong to a track? 
1. A strict definition is that all the segments are connected due to overlapping objects.
2. A looser definition is that a track is merely a logical grouping of arbitrary segments for purpose of referencing a group of segments. Perhaps a track may just be a group of segments that should be plotted together.

Tracks of the first definition, groups of connected segments, can be automatically inferred from just the object and segment tables if no track table is explicitly given.

Using tracks to imply a gap closing event is unclear in terms of connectivity, complicates the definition of tracks, and is inconsistent with the split and merge examples where connectivity is explicit.

**Comment by sbesson** [comment]
I would agree with @mkitti there are 2 main ways to resolve the ambiguities in the case of mixed gap closing & merge-split in a non-ambiguous way:
- either enforce every object belongs to at most one segment and come back to the initial proposal of an event table
- or enforce that all segments belonging to the same non-linear track must be connected as stated above

In the latter case, the implications for the typical computational workflow described in https://github.com/CellMigStandOrg/Tracks/blob/master/index.md#introduction is that the segment linking step would also have be involved in updating the segments table originally created by the linking algorithm.

One remark regarding the isolated gap-closing, I also see a four alternative representing this scenario using 3 segments:

Segment_ID |  Object_ID
-----------|------------
 1         |    1
 1         |    2
 2         |    3
 2         |    4
 3         |    2
 3         |    3

Here the segment 3 directly represents the "gap closing" and would be created by the segment linking step. One could even imagine annotating this segment in an additional column. Does this make sense?

**Comment by mkitti** [comment]
@sbesson I concur. Also, I do not think we should concern ourselves too much about what the linker is doing and how it works. It should not be of concern to us whether the linker only considers adjacent frames in a pairwise fashion or uses some kind of rolling window or motion prediction approach. We should merely focus on making sure the linker can clearly communicate what is linked.

As all the approaches including the the fourth proposal that @sbesson gave conform to the table and are unambiguous, all are valid ways of conveying similar information. For specific applications, which we need not fully enumerate here, one of the proposals may make more sense than the others.

In this "segments" table segment_ids are repeated. Rather than an additional column, I think another table that annotates segments would be appropriate.  The segmentation annotation table, however, does not need to be in the minimal standard.

Also due the difficult in phrasing the last statement, I propose the segment_id, object_id table not be called the segments table. Perhaps it should be called the linking table.

**Comment by pcmasuzzo** [comment]
Thanks @mkitti and @sbesson - these are great points. 
I do see now the ambiguity in the gap-closing event representation.
I do agree that all four suggestions above are valid alternatives (A - B - C from @mkitti and last one from @sbesson, which I will now call D). 

However, because key point should be: overlap of **Oject_ID** reference as explicit event marker, I suggest we keep A B and D as options and skip C. Sounds reasonable?

As for @sbesson proposal D and the extra column for the annotation of the segment, I would suggest to go for this refactoring:

- we rename the current **segments table** into **links table** (also to avoid confusion with segments as in: identified objects after segmentation) 
- we add an optional table (which [may ](https://tools.ietf.org/html/rfc2119) be in the package) called **segments table** containing columns with segments annotations (not sure what it would contain though).

I will make a PR addressing this issue and will take it from there.

**Comment by sbesson** [comment]
Fixed by #8. Closing.
