### ISSUE TITLE
Tabular data package as a tracks format

### ISSUE THREAD

**Issue by sbesson** [CellMigStandOrg/Tracks#7]
Discussed at the CMSO call with @pcmasuzzo @joshmoore, in preparation of the first release of the specification, we want to have some minimal description of the [tabular data package](http://specs.frictionlessdata.io/tabular-data-package/) as our current format for expressing tracks.

**Comment by pcmasuzzo** [comment]
So the plan on this side is as follows:

Work on cell_track_dpkg [branch_spec_0.1](https://github.com/CellMigStandOrg/cell_track_dpkg/tree/spec_0.1).

First question however is: do we still use examples collected [here](https://github.com/CellMigStandOrg/cell_track_dpkg/tree/spec_0.1/examples)?

Most of the software I used for those data sets produce a single tracking file listing tracks and their coordinates in time. The segmentation step (and therefore the *objects_table*) is implicit (skipped).
I am struggling a bit...
