### ISSUE TITLE
Need to describe explicitly minimum specification

### ISSUE THREAD

**Issue by pcmasuzzo** [CellMigStandOrg/Tracks#9]
Nowhere in the specification is the minimum representation of tracks described.

Need to specify the **minimum** representation of this specification:
{objects + links} `(MUST)`
{+ tracks} `(MAY)`

**Comment by gsergeant** [comment]
_Links_ could be changed to `(MAY)` as well.

Potentially users can perform pure segmentation on their images, 
getting and uploading only the detected objects table to the repository.

**Comment by pcmasuzzo** [comment]
Good call, @gsergeant.

Data producers/consumers might indeed be interested *only* in objects (segmentation results).
However, semantically speaking, that would not be a **Tracks** specification anymore. 

To me, this issues goes back to the very first CMSO workshop in Ghent (March 2016), when a discussion took place regarding `level0` positions files and `level1` trajectories files.
Could not find a better figure, but this is what I am referring to:
![image](https://cloud.githubusercontent.com/assets/10747332/23787067/878da5e6-0570-11e7-81db-20829f4b40a7.png)

So the question is:
do we add levels to this specification?
or do we instead make the _Links_ optional (as in `MAY`) - and we encode this `level` concept into the (minimum vs non-minimum) requirements?

Happy to chat about this.

**Comment by proudot** [comment]
IMO,  links must be specified if we call them track (MUST). However, you can absolutely track and find zero link: if the parameter are out of wack or if the lifetimes are not sampled. How does an empty list would look like ?

OK for MAY for the tracks object.

**Comment by pcmasuzzo** [comment]
@proudot this is an edge case that we can definitely try to resolve later, e.g. in resolving issue #11
